### ISSUE TITLE
Contributing plugins - what would be of interest

### ISSUE THREAD

**Issue by practicalli-john** [rafaeldelboni/nvim-fennel-lsp-conjure-as-clojure-ide#15]
Which of the following plugins would be of used to contribute as pull requests to this configuration

- [x] telescope-file-browser - browse, create, rename, delete files and directories throughout the filespace (I find this very useful)
- [x] telescope-env - list environment variables
- [ ] nvim-tree - visual file system browser (Lua version of Nerdtree)
- [x] todo-comments - highlight TODOD, FIXME, etc in buffers
- [x] startup.nvim - themes to load when nvim started without a file
- [ ] numb.nvim - peek at a line number
- [x] nvim-comment - toggle line comments with visual select and motions

I have been using these for a few days in [my experimental configuration](https://github.com/practicalli/neovim-config-redux) and they seem to work.  There are some other plugins that are interesting, but still evaluating those.

**Comment by rafaeldelboni** [comment]
Personally, I use nerdtree and nerdcomment and I was wondering if were replacements in lua for those :)

Quick question, can't you replace nvim-tree with telescope-file-browser? They look very similar apart from the tree view.

I really like all of those, I just think numb.nvim is a very personal choice maybe we could leave this one.

**Comment by rafaeldelboni** [comment]
Thanks a lot, that would be a great addition

**Comment by rafaeldelboni** [comment]
Hey I was thinking, do you think we should rename or move this more complex setup to a new name? Like simpler? Like LunarVim or DoomEmacs did?

I don't like the name of this repo, but I didn't expected it get this attention :)

**Comment by practicalli-john** [comment]
The name could be a little shorter perhaps :) 

Also, I assume the config doesnt need to be in the `.config/nvim` directory. Being in a dot folder at first made it a little confusing when linking to the configuration from the actual .config/nvim directory

**Comment by rafaeldelboni** [comment]
`anise.nvim`?
https://www.collinsdictionary.com/us/dictionary/english/anise-camphor

I'm down to change the folder structure, what you recommend?

Thinking we can create a new repo and update the references to the new one on the conjure/lsp wikis.

**Comment by rafaeldelboni** [comment]
I will close this issue, feel free to reopen if you need anything related to this again :)
I think you following those changes in https://github.com/practicalli/neovim-config-redux right?

**Comment by practicalli-john** [comment]
Apologies, my health has reduced the amount extra work I could do over the last few months.  I haven't had much time to resolve some of the outstanding functionality I need to use Neovim as my main development tool, so my experimentation with packages and settings in neovim-config-redux has stalled, although hope to pick that up again when my health allows.

**Comment by rafaeldelboni** [comment]
Hey, I hope you get better soon, thanks again for all your work for the community.
