### ISSUE TITLE
clojure-lsp in neovim is not navigating to function definitions/namespaces

### ISSUE THREAD

**Issue by rajcspsg** [rafaeldelboni/nvim-fennel-lsp-conjure-as-clojure-ide#18]
I'm using neovim with clojure lsp for clojure development. My neovim config are exactly same as this [repo](https://github.com/rafaeldelboni/nvim-fennel-lsp-conjure-as-clojure-ide).

The autosuggesting is working fine with this configuration. But when I like to navigate to function/namespace definitions, it is not working.

For example, I've local repository which it in [github](https://github.com/rajcspsg/guestbook) here. Let's say I'm working on the file src/clj/guestbook/routes/home.clj. I'm trying to click and navigate to `save-message!` in [line 39](https://github.com/rajcspsg/guestbook/blob/main/src/clj/guestbook/routes/home.clj#L39). But command + click or ctrl + click is not working. The link is [here](https://i.stack.imgur.com/Kv5Ek.jpg).

Similarly when I try to navigate the namespaces, command + click is enabled as in the [image](https://i.stack.imgur.com/IZVUO.jpg).

But when I click the namespace, it open the browser with link guestbook.middleware as in the [image](https://i.stack.imgur.com/x2urN.png).

I've asked the same question in the [stackoverflow](https://stackoverflow.com/questions/75190136/clojure-lsp-in-neovim-is-not-navigating-to-function-definitions-namespaces) as well

**Comment by rafaeldelboni** [comment]
I replied in the stackoverflow 😬
