### ISSUE TITLE
Is there a way to jump to a new definition in a new tab and a way to go back?

### ISSUE THREAD

**Issue by zendevil** [rafaeldelboni/nvim-fennel-lsp-conjure-as-clojure-ide#5]
When we jump to a definition, it jumps in the same buffer. Is there a way to jump to a definition in a new tab and also to go back from where we came from when jumping in the same tab?

**Comment by rafaeldelboni** [comment]
Hey thanks for you interest in this repo :)

I think this is the default nvim behavior, you can overwrite it, as discussed here:
https://neovim.discourse.group/t/go-to-definition-in-new-tab/1552

But this is for LSP go-to definition, but for conjure go-to definition I think that is another story, you would need to talk with the [developer](https://github.com/Olical/conjure/)

**Comment by rafaeldelboni** [comment]
I will close this issue, feel free to reopen if you need anything related to this again :)
